---
title: "Presentation Regressions"
author: "Quinn Bankson"
date: "2023-04-16"
output: html_document
---

```{r setup, include=FALSE}

```

```{r}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
library(tidyr)
library(naniar)
```

```{r}
data <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/presentationdata.csv")
```
```{r}
head(data)
colnames(data)
```

```{r}
#vis_miss(data)
```

```{r}
data <- data %>% 
  mutate(distance_km = distance_to_nearest_plant / 1000)

write_csv(merged_data, file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Cleaned Merged Data/fullplusmoke.csv")

data_s <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Cleaned Merged Data/fullplusmoke.csv")

smoking <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Norwood/smoking_cleaned.csv")

smoking <- smoking %>% rename(fips = geo_id)


data_10 <- data_s %>%
  arrange(distance_km) %>% # sort by distance_km
  slice(1:round(n() * 0.1)) # keep top 10% of observations

data_50 <- data_s %>%
  arrange(distance_km) %>% # sort by distance_km
  slice(1:round(n() * 0.5)) # keep top 50% of observations


```


```{r}
pr2model <- lm(mortality_resp ~ median_aqi + max_aqi + good_days + moderate_days + unhealthy_for_sensitive_groups_days + unhealthy_days + hazardous_days +days_ozone + days_no2 + distance_km, data = data)
summary(pr2model)
```
```{r}
pr1model <- lm(mortality_resp ~ median_aqi + unhealthy_days + hazardous_days + days_no2 + distance_km, data = data)
summary(pr1model)
```


```{r}
# County fixed effects and smoking, control for states with high smoking rates, rural indicator, 

```

```{r}
final_mod1 <-lm(mortality_resp ~ distance_km, data = data)

summary(final_mod1)
```
```{r}
final_mod10 <-lm(mortality_resp ~ distance_km, data = data_10)

summary(final_mod10)
```
```{r}
vis_miss(data_10)
```
```{r}
vis_miss(data_50)
```



```{r}
final_mod50 <-lm(mortality_resp ~ distance_km, data = data_50)

summary(final_mod50)
```


```{r smoking data} 
smoking_mod1 <-lm(mortality_resp ~ distance_km + current_smokers, data = data_s)

summary(smoking_mod1)

```
```{r}
smoking_mod2 <- lm(mortality_resp ~ distance_km + current_smokers + state.x, data = data_s)

summary(smoking_mod2)
```

```{r}
smoking_mod10 <- lm(mortality_resp ~ distance_km + current_smokers, data = data_10)

summary(smoking_mod10)
```

```{r}
smoking_mod10 <- lm(mortality_resp ~ distance_km + current_smokers, data = data_50)

summary(smoking_mod10)
```

