---
title: "Final_Mark_Down"
author: "Quinn Bankson"
date: "2023-05-04"
output: html_document
---

```{r setup}
```

```{r}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
```

```{r}
coalplants <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/CoalPlants2.csv")

# coalplants <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/CoalPlants2.csv")
```

```{r}
colnames(coalplants)
coalplants <- clean_names(coalplants)
coalplants <- coalplants %>% filter(country == "United States")
coalplants <- coalplants %>% select(parent_id, unit, subnational_unit_province_state, plant, status, year, local_area_taluk_county, latitude, longitude )
coalplants <- rename(coalplants, county = local_area_taluk_county)
```

```{r}
counties <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/uscounties.csv")
head(counties)
colnames(counties)
county_center <- counties %>% select(county, state_name, lat, lng)
```

```{r}
coalplants_op <- coalplants %>% filter(status == "operating")
coalplants_op <- distinct(coalplants_op, plant, .keep_all = TRUE)
```

```{r}
coal_plants <- coalplants_op %>% select("latitude", "longitude","subnational_unit_province_state", "plant", "county")
coal_plants <- rename(coal_plants, long= longitude, lat = latitude)
coal_plants <- rename(coal_plants, state = subnational_unit_province_state, name = plant)
county_centroids <- county_center
county_centroids <- rename(county_centroids, state = state_name)
```

```{r}
#install.packages("geosphere")
library(geosphere)
library(dplyr)
library(naniar)

county_centroids <- rename(county_centroids, long = lng)

coal_plants <- coal_plants %>% 
  filter(!is.na(long))
coal_plants <- coal_plants %>% 
  filter(!is.na(lat))

county_centroids <- county_centroids %>% 
  filter(!is.na(long))
county_centroids <- county_centroids %>% 
  filter(!is.na(lat))
```

```{r}
library(dplyr)
library(geosphere)

# filtering to be sure
coal_plants <- na.omit(coal_plants)


distances <- geosphere::distm(county_centroids[, c("long", "lat")], coal_plants[, c("long", "lat")])

# minimum distance per county
min_distances <- apply(distances, 1, min)

# add the new column to the county_centroids dataframe using mutate
county_centroids <- county_centroids %>% 
  mutate(distance_to_nearest_plant = min_distances)

coords_distance <- county_centroids
```

```{r, warning = FALSE}
# filtering to be sure, this code will atatch plant name as well as the minimum distance
coal_plants <- na.omit(coal_plants)

 #repeating earlier to be sure
distances <- geosphere::distm(county_centroids[, c("long", "lat")], coal_plants[, c("long", "lat")])

# minimum distance and corresponding plant name per county
min_distances <- apply(distances, 1, min)
names_of_nearest_plants <- apply(distances, 1, function(x) coal_plants$name[which.min(x)])

# add new columns to the county_centroids dataframe using mutate
county_centroids <- county_centroids %>% 
  mutate(distance_to_nearest_plant = min_distances,
         name_of_nearest_plant = names_of_nearest_plants)

coords_distance <- county_centroids 

write_csv(county_centroids, "/Users/mac/Documents/My Tableau Repository/countycoords.csv")
write_csv(coal_plants, "/Users/mac/Documents/My Tableau Repository/coalplantcoords.csv")

#write_csv(county_centroids, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/countycoords.csv")

#write_csv(coal_plants, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/coalplantcoords.csv")

```

```{r}
summary(county_centroids$distance_to_nearest_plant)
```

```{r}
### This concludes the feature engineering in which the minimum distance from each county centroid to the nearest coal fired power plant is calculated and compiled along with the name of the nearest plant into a tibble called countycoords.csv. This csv has record of 3143 US counties and their distance. ### 
```

```{r}
### The next section of the .rmd will compile 3196 health outcomes (3143 of which correspond to the 3143 US counties that are observed) and aqi data from 1036 observed US counties as well. A crosswalk was used to match values by FIPS codes. 
```


```{r libraries}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
#install.packages("tidyr")
library(tidyr)
```

```{r read files}
crossw <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/countycrosswalk.csv")

aqi <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/annual_aqi_by_county_2014.csv")

outcomes <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/health_outcomes_2014.csv")

#outcomes <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/health_outcomes_2014.csv")
```
```{r correct names}

colnames(crossw)[1] <- "County"
colnames(crossw)[2] <- "State"
colnames(crossw)[3] <- "FIPS"

crossw <- crossw %>% select(County, State, FIPS)

crossw <- crossw %>%
  filter(County != "County Name")
```

```{r}

crossw <- crossw %>%
  mutate(County = str_to_title(tolower(County)))
```


```{r}
outcomes <- outcomes %>%
  separate(Location, into = c("County", "State"), sep = ", ", remove = FALSE)

outcomes <- outcomes %>%
  filter(!is.na(State))

outcomes$County <- str_replace(outcomes$County, " County", "")

outcomes$County <- str_replace(outcomes$County, " Parish", "")

outcomes$County <- str_replace(outcomes$County, "Saint ", "St. ")
```

```{r}
# join AQI and Outcomes, there will be all 3000+ Outcomes visible and only 1000ish AQI present

joined_dv_iv <- left_join(outcomes, aqi, by = c("County" = "County", "State" = "State"))
view(joined_dv_iv)
```


```{r}
joined_dv_iv <- clean_names(joined_dv_iv)

# I intend to join the countycoords tibble which has county, state, lat, long, distance_to_nearest_plant, name_of_nearest_plant 

centroidsandplants <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/QBCleanerData/countycoords.csv")

#centroidsandplants <- read_csv("/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/coalplantcoords.csv")
```

```{r}
final <- left_join(joined_dv_iv, centroidsandplants, by = c("county" = "county", "state" = "state"))
view(final)
```



```{r}
library(naniar)

vis_miss(final)
```

```{r}
write_csv(final, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/presentationdata.csv")

#write_csv(final, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/health_aqi_coal_distance.csv")
```


```{r}
colnames(final)

```

```{r}
### At this point in the process, we had a merged data set containing health outcomes, air quality, and distance from operating coal plants by county for 3143 counties in the United States. We established health outcomes as our dependent variables ("mortality_resp", "perc_mortality_change_resp", "mortality_ast", "perc_mortality_change_ast", "mortality_lung", "perc_mortality_change_lung"). The remaining variables were independent variables and controls of interest to us. We began conducting some basic regressions. ###
```



```{r}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
library(tidyr)
library(naniar)
```

```{r}
data <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/presentationdata.csv")
```
```{r}
head(data)
colnames(data)
```

```{r}
# Checking to see which variables would create a regression using 1000+ observations and which variables would create a regression using 3000+ observations. 

vis_miss(data)
```

```{r}
data <- data %>% 
  mutate(distance_km = distance_to_nearest_plant / 1000)

pr1model <- lm(mortality_resp ~ median_aqi + unhealthy_days + hazardous_days + days_no2 + distance_km, data = data)
summary(pr1model)
```

```{r}
pr2model <- lm(mortality_resp ~ median_aqi + max_aqi + good_days + moderate_days + unhealthy_for_sensitive_groups_days + unhealthy_days + hazardous_days +days_ozone + days_no2 + distance_km, data = data)
summary(pr2model)
```

```{r}

### After observing some basic regressions, we found our R-squared values to be very low, but our distance variable to be significant at at least the 0.01 level frequently. This lead us to believe that our regressions accounted for very little of the explanation for health outcomes across US counties, but distance still was an important contributor. Our regressions advanced to include smoking data, control by county, look at the closest 10 percent of county centroids to plants, and look at the top 50 percent of closest county centroids to plants. ###

```

```{r}
data <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/presentationdata.csv")
```

```{r}
head(data)
colnames(data)
```

```{r}
library(dplyr)
library(magrittr)

data <- data %>% 
  mutate(distance_km = distance_to_nearest_plant / 1000)

# The file smoking_cleaned provides more independent variables for control. The crucial variable provided by this data set is the crude percent of adults who currently smoke in 2020.

smoking <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Norwood/smoking_cleaned.csv")

smoking <- smoking %>% rename(fips = geo_id)

data <- data %>%
  mutate(fips = sprintf("%05d", fips))

# Join the two data sets using the FIPS code

merged_data <- data %>%
  left_join(smoking, by = c("fips", "county"))

merged_data <- merged_data %>%
  rename(state = state.x, state_abrv = state.y)

#write_csv(merged_data, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/health_aqi_coal_distance.csv")

write_csv(merged_data, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/QBCleanerData/health_aqi_coal_smoking.csv")

#data_s <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Cleaned Merged Data/fullplusmoke.csv") 

```

```{r}
data_10 <- merged_data %>%
  arrange(distance_km) %>% # sort by distance_km
  slice(1:round(n() * 0.1)) # keep top 10% of observations

data_50 <- merged_data %>%
  arrange(distance_km) %>% # sort by distance_km
  slice(1:round(n() * 0.5)) # keep top 50% of observations
```

```{r}
exmodel <- lm(mortality_resp ~ median_aqi + max_aqi + good_days + moderate_days + unhealthy_for_sensitive_groups_days + unhealthy_days + hazardous_days +days_ozone + days_no2 + distance_km, data = merged_data)
summary(exmodel)
```

```{r}
exmodel2 <- lm(mortality_resp ~ median_aqi + unhealthy_days + hazardous_days + days_no2 + distance_km, data = data)
summary(exmodel2)
```

```{r}
final_mod1 <-lm(mortality_resp ~ distance_km, data = data)

summary(final_mod1)
```

```{r}
final_mod10 <-lm(mortality_resp ~ distance_km, data = data_10)

summary(final_mod10)
```


```{r}
final_mod50 <-lm(mortality_resp ~ distance_km, data = data_50)

summary(final_mod50)
```


```{r}
smoking_mod1 <-lm(mortality_resp ~ distance_km + current_smokers, data = merged_data)

summary(smoking_mod1)
```


```{r}
smoking_mod2 <- lm(mortality_resp ~ distance_km + current_smokers + state, data = merged_data)

summary(smoking_mod2)
```


```{r}
smoking_mod10 <- lm(mortality_resp ~ distance_km + current_smokers, data = merged_data)

summary(smoking_mod10)
```


```{r}
smoking_mod50 <- lm(mortality_resp ~ distance_km + current_smokers, data = merged_data)

summary(smoking_mod50)
```

