---
title: "Cleaning Darkorchid4 Data"
author: "Eric Leinweber"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Setting the Working Directory}
#setwd("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/")
```


```{r}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
library(tidyr)
```


```{r Cleaning Health Outcomes Data}
#reading in the data 
asthma_outcomes <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/Health Outcomes/Asthma_Mortality_UNCLEAN.csv")
resp_outcomes <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/Health Outcomes/ChronicRespiratoryDiseases_Mortality_UNCLEAN.csv")
cwp_outcomes <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/Health Outcomes/CoalWorkersPneumoconiosis_Mortality_UNCLEAN.csv")
lung_outcomes <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/Health Outcomes/LungDisease_Mortality_UNCLEAN.csv")

#selecting and renaming mortality rate rows for clarity 
asthma_outcomes <- asthma_outcomes  %>% select(c("Location", "FIPS", `Mortality Rate, 2014*`, `% Change in Mortality Rate, 1980-2014`)) %>% mutate("mortality_ast_2014" = `Mortality Rate, 2014*`, "perc_mortality_change_ast" = `% Change in Mortality Rate, 1980-2014`) %>% select(-c(`% Change in Mortality Rate, 1980-2014`, `Mortality Rate, 2014*`))

cwp_outcomes <- cwp_outcomes  %>% select(c("Location", "FIPS", `Mortality Rate, 2014*`, `% Change in Mortality Rate, 1980-2014`)) %>% mutate("mortality_cwp_2014" = `Mortality Rate, 2014*`, "perc_mortality_change_cwp" = `% Change in Mortality Rate, 1980-2014`) %>% select(-c(`% Change in Mortality Rate, 1980-2014`, `Mortality Rate, 2014*`))

lung_outcomes <- lung_outcomes  %>% select(c("Location", "FIPS", `Mortality Rate, 2014*`, `% Change in Mortality Rate, 1980-2014`)) %>% mutate("mortality_lung_2014" = `Mortality Rate, 2014*`, "perc_mortality_change_lung" = `% Change in Mortality Rate, 1980-2014`) %>% select(-c(`% Change in Mortality Rate, 1980-2014`, `Mortality Rate, 2014*`))

resp_outcomes <- resp_outcomes  %>% select(c("Location", "FIPS", `Mortality Rate, 2014*`, `% Change in Mortality Rate, 1980-2014`)) %>% mutate("mortality_resp_2014" = `Mortality Rate, 2014*`, "perc_mortality_change_resp" = `% Change in Mortality Rate, 1980-2014`) %>% select(-c(`% Change in Mortality Rate, 1980-2014`, `Mortality Rate, 2014*`))

#merging all health outcomes data into one, complete dataset
merge1 <- merge(asthma_outcomes, cwp_outcomes, by = c("FIPS", "Location"))
merge2 <- merge(merge1, lung_outcomes, by = c("FIPS", "Location"))
health_outcomes <- merge(merge2, resp_outcomes, by = c("FIPS", "Location"))

#using stringr to remove ranges in mortality rate variables
health_outcomes$mortality_ast_2014 <- stringr::str_extract(health_outcomes$mortality_ast, "^.{5}")
health_outcomes$mortality_resp_2014 <- stringr::str_extract(health_outcomes$mortality_resp, "^.{5}")
health_outcomes$mortality_lung_2014 <- stringr::str_extract(health_outcomes$mortality_lung, "^.{5}")
health_outcomes$mortality_cwp_2014 <- stringr::str_extract(health_outcomes$mortality_cwp, "^.{5}")

#using stringr to remove ranges in percent mortality rate variables
health_outcomes$perc_mortality_change_ast <- stringr::str_extract(health_outcomes$perc_mortality_change_ast, "^.{6}")
health_outcomes$perc_mortality_change_resp <- stringr::str_extract(health_outcomes$perc_mortality_change_resp, "^.{6}")
health_outcomes$perc_mortality_change_cwp <- stringr::str_extract(health_outcomes$perc_mortality_change_cwp, "^.{6}")
health_outcomes$perc_mortality_change_lung <- stringr::str_extract(health_outcomes$perc_mortality_change_lung, "^.{6}")

#using stringr to remove remaining parentheses in percent mortality rate variables
health_outcomes$perc_mortality_change_ast<- gsub("[()]", "", health_outcomes$perc_mortality_change_ast)
health_outcomes$perc_mortality_change_resp<- gsub("[()]", "", health_outcomes$perc_mortality_change_resp)
health_outcomes$perc_mortality_change_cwp<- gsub("[()]", "", health_outcomes$perc_mortality_change_cwp)
health_outcomes$perc_mortality_change_lung<- gsub("[()]", "", health_outcomes$perc_mortality_change_lung)

#changing all health outcome variables to numeric, now that there are no parentheses and range data
health_outcomes$mortality_ast_2014 <- as.numeric(health_outcomes$mortality_ast_2014)
health_outcomes$mortality_resp_2014 <- as.numeric(health_outcomes$mortality_resp_2014)
health_outcomes$mortality_lung_2014 <- as.numeric(health_outcomes$mortality_lung_2014)
health_outcomes$mortality_cwp_2014 <- as.numeric(health_outcomes$mortality_cwp_2014)
health_outcomes$perc_mortality_change_ast <- as.numeric(health_outcomes$perc_mortality_change_ast)
health_outcomes$perc_mortality_change_resp <- as.numeric(health_outcomes$perc_mortality_change_resp)
health_outcomes$perc_mortality_change_cwp <- as.numeric(health_outcomes$perc_mortality_change_cwp)
health_outcomes$perc_mortality_change_lung <- as.numeric(health_outcomes$perc_mortality_change_lung)

#removing "Parish," "County," and replacing "Saint" with "St." for all county names
health_outcomes <- health_outcomes %>%
  separate(Location, into = c("County", "State"), sep = ", ", remove = FALSE) %>% select(-c("Location"))

health_outcomes$County <- str_replace(health_outcomes$County, " County", "")

health_outcomes <- health_outcomes %>% mutate(County = str_replace(County, " Parish", ""))

health_outcomes <- health_outcomes %>% mutate(County = str_replace(health_outcomes$County, "Saint ", "St. "))

#removing NA's created from separating into state/county... these NA's represent cumulative state data for each state/the US, which is not needed for our analysis
health_outcomes <- health_outcomes %>%
  filter(!is.na(State))

#creating cleaned CSV into shared folder
write_csv(health_outcomes, "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/health_outcomes_CLEAN.csv")
```

```{r Cleaning AQI Data}
#reading in the data 
aqi_2014 <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/annual_aqi_by_county_2014.csv")

#this data is already cleaned, so creating a new CSV into the shared folder
write_csv(aqi_2014, "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/aqi_2014_CLEAN.csv")

```

```{r Cleaning Coal Plant Data}
coal_plants <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/CoalPlants.csv")

#filtering for just the United States, as this dataset contains infornmation on the entire world
coal_plants <- coal_plants %>% filter(Country == "United States")

#this data is already cleaned, as we only need the latitude/longitude of each coal plant for the purposes of this data
write_csv(coal_plants,  "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/coal_plants_CLEAN")
```

```{r Cleaning Smoking Data}
smoking <- read.csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Raw_Unprocessed/smoking.csv")

#Deleting the first row
smoking <- smoking[-c(1), ]

#Clean names 
smoking <- clean_names(smoking)
names(smoking)

#Removing unnecessary columns
smoking <- smoking %>% select(-one_of('geography_type_description', 'data_time_period', 'geographic_vintage', 'data_source', 'selected_location', 'formatted_geo_id'))

smoking <- smoking %>% rename_at('sits_in_state', ~'state') 
smoking <- smoking %>% rename_at('geography_name', ~'county')


#Chaning current_smokers to be numeric
smoking <- smoking %>% mutate(current_smokers = as.numeric(current_smokers))

#creating cleaned CSV into shared folder
write.csv(smoking, "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/DATA/Clean/smoking_CLEAN.csv", row.names=FALSE)
```

