---
title: "HealthCrosswalk"
author: "Quinn Bankson"
date: "2023-04-13"
output: html_document
---

```{r setup}
```


```{r libraries}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
#install.packages("tidyr")
library(tidyr)
```

```{r read files}
crossw <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/countycrosswalk.csv")

aqi <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/annual_aqi_by_county_2014.csv")

outcomes <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/health_outcomes_2014.csv")
```

```{r correct names}
colnames(crossw)[1] <- "County"
colnames(crossw)[2] <- "State"
colnames(crossw)[3] <- "FIPS"

crossw <- crossw %>% select(County, State, FIPS)

crossw <- crossw %>%
  filter(County != "County Name")

```

```{r}

crossw <- crossw %>%
  mutate(County = str_to_title(tolower(County)))

```


```{r}
outcomes <- outcomes %>%
  separate(Location, into = c("County", "State"), sep = ", ", remove = FALSE)

outcomes <- outcomes %>%
  filter(!is.na(State))

outcomes$County <- str_replace(outcomes$County, " County", "")

outcomes$County <- str_replace(outcomes$County, " Parish", "")

outcomes$County <- str_replace(outcomes$County, "Saint ", "St. ")

```

```{r}
# join AQI and Outcomes, there will be all 3000+ Outcomes visible and only 1000ish AQI present

joined_dv_iv <- left_join(outcomes, aqi, by = c("County" = "County", "State" = "State"))
view(joined_dv_iv)
```

```{r}
# I intend to join the countycoords tibble which has county, state, lat, long, distance_to_nearest_plant, name_of_nearest_plant 

joined_dv_iv <- clean_names(joined_dv_iv)

centroidsandplants <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/QBCleanerData/countycoords.csv")

```
```{r}
final <- left_join(joined_dv_iv, centroidsandplants, by = c("county" = "county", "state" = "state"))
view(final)
```

```{r}
library(naniar)

vis_miss(final)
```

```{r}
write_csv(final, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/presentationdata.csv")
```

```{r}
colnames(final)

```

```{r}

coal_plants_forjoin <- coal_plants

new_cols <- c("fips", "location", "mortality_resp", "perc_mortality_change_resp", 
              "mortality_ast", "perc_mortality_change_ast", "mortality_lung",
              "perc_mortality_change_lung", "year", "days_with_aqi", "good_days",
              "moderate_days", "unhealthy_for_sensitive_groups_days", "unhealthy_days",
              "very_unhealthy_days", "hazardous_days", "max_aqi", "x90th_percentile_aqi",
              "median_aqi", "days_co", "days_no2", "days_ozone", "days_pm2_5", "days_pm10",
              "distance_to_nearest_plant", "name_of_nearest_plant")

coal_plants_forjoin[, new_cols] <- NA

colnames(coal_plants_forjoin)


```
```{r}

final_forjoin <- final

new_cols2 <- c( "name")

final_forjoin[, new_cols2] <- NA

colnames(final_forjoin)
```
```{r}
coal_plants_forjoin <- coal_plants_forjoin %>%
  select(fips, location, county, state, mortality_resp, perc_mortality_change_resp, 
         mortality_ast, perc_mortality_change_ast, mortality_lung, perc_mortality_change_lung, 
         year, days_with_aqi, good_days, moderate_days, unhealthy_for_sensitive_groups_days, 
         unhealthy_days, very_unhealthy_days, hazardous_days, max_aqi, x90th_percentile_aqi, 
         median_aqi, days_co, days_no2, days_ozone, days_pm2_5, days_pm10, lat, long, 
         distance_to_nearest_plant, name_of_nearest_plant, name)

final_forjoin <- final_forjoin %>%
  select(fips, location, county, state, mortality_resp, perc_mortality_change_resp, 
         mortality_ast, perc_mortality_change_ast, mortality_lung, perc_mortality_change_lung, 
         year, days_with_aqi, good_days, moderate_days, unhealthy_for_sensitive_groups_days, 
         unhealthy_days, very_unhealthy_days, hazardous_days, max_aqi, x90th_percentile_aqi, 
         median_aqi, days_co, days_no2, days_ozone, days_pm2_5, days_pm10, lat, long, 
         distance_to_nearest_plant, name_of_nearest_plant, name)

final_fortableau <- rbind(final_forjoin, coal_plants_forjoin)

final_fortableau$is_plant <- ifelse(is.na(final_fortableau$name) | final_fortableau$name == "", 0, 1)
```

```{r}

write_csv(final_fortableau, "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/fortableau2.csv")
```

