---
title: "MergeScriptQB"
author: "Quinn Bankson"
date: "2023-01-30"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(janitor)
rawdata <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/DarkOrchid/Bankson/InitialData/QBGlobalCoalTrackData.csv")
USrawdata <- rawdata %>% filter(Country == "United States")
USdata <- clean_names(USrawdata)
names(USdata)
USdata <- USdata %>% 
    rename("state" = "subnational_unit_province_state",
           "county" = "local_area_taluk_county")
us_coal <- USdata %>% select("state", "year","county", "status", "combustion_technology", "emission_factor_kg_of_co2_per_tj", "annual_co2_million_tonnes_annum", "lifetime_co2")

## write_csv(us_coal, file = "/Users/mac/Documents/R Assignments PLCY 715/DarkOrchid/Bankson/coal_dta_clean1.csv")
```
```{r}

grouped<- us_coal %>% group_by(state) %>% summarize(stateco2 = sum(lifetime_co2))
grouped

new_row1 <-tibble(state="Idaho", stateco2=0.0)
new_row2 <-tibble(state="Vermont", stateco2=0.0)
new_row3 <-tibble(state="Rhode Island", stateco2=0.0)


grouped<-add_row(grouped, new_row1)
grouped<-add_row(grouped, new_row2)
grouped<-add_row(grouped, new_row3)

grouped<-filter(grouped, state != "Michigan")
grouped<-filter(grouped, state != "MIchigan")
grouped<-filter(grouped, state != "Puerto Rico")
grouped<-filter(grouped, state != "Virgin Islands")

new_row4 <-tibble(state="Michigan", stateco2=0.0)
new_row5 <-tibble(state="District of Columbia", stateco2=0.0)
grouped<-add_row(grouped, new_row4)
grouped<-add_row(grouped, new_row5)
write_csv(grouped, file = "/Users/mac/Documents/R Assignments PLCY 715/grouped_data.csv")
grouped 
```

