---
title: "Darkorchid4_Merged_Data"
output: html_document
date: "2023-02-20"
---
```{r}
library(tidyverse)
library(tidycensus)
library(ggplot2) 
library(ggmap)
library(geosphere)
library(sp)
library(rgdal)
library(rgeos)
library(maps)
library(GADMTools)
library(maptools)
library(countrycode)
library(usmap)
install.packages("ggpubr")
library(patchwork)
data("world.cities")
head(world.cities)

```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)

Hathaway_data <- new_cleaned_data_excel_715 
Hathaway_data <- clean_names(Hathaway_data)
#reading in Paige's data and cleaning variable names

Leinweber_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Leinweber/usretechnicalpotential.csv") %>% clean_names()
#reading in Eric's data and cleaning variable names

Norwood_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHubRepository/final-team-projects-darkorchid/DarkOrchid/Norwood/usa_lung_cancer_by_state.csv") %>% clean_names()
Norwood_data <- Norwood_data[-c(52:92), ] %>% select(-c("x3", "x4", "x5", "x6", "x7"))
#reading in Betsy's data, cleaning variable names, and getting rid of NA columns/rows

Bankson_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Bankson/QBCleanerData/grouped_data.csv") %>% clean_names()
#reading in Quinn's data and cleaning variable names

Merged_Darkorchid4_Data <- merge(Hathaway_data, Leinweber_data, by = "state")
Merged_Darkorchid4_Data <- merge(Merged_Darkorchid4_Data, Norwood_data, by="state")
Merged_Darkorchid4_Data <- merge(Merged_Darkorchid4_Data, Bankson_data, by = "state")
#merging all data frames by "state" variable

write_csv(Merged_Darkorchid4_Data, "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Merged_DarkOrchid4_Dataset.csv")


```


```{r}

data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Merged_DarkOrchid4_qDataset.csv")

data <- data %>% rename(reps_disease_death = chronic_lower_res "respiratory_disease_deaths_per_100_000_people")

names(data)

data %>% ggplot(aes(x = allpower_g_wh, y = reps_disease_death)) +
  geom_point()

usa <- sf::st_read(system.file("shape/nc.shp", package="sf"))

p1 <- plot_usmap(data = data, values ="stateco2") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Total CO2 emissions", label = scales::comma) + 
  theme(legend.position = "right")
p2 <- plot_usmap(data = data, values ="allpower_g_wh") + 
scale_fill_continuous(low = "white", high = "blue",name = "Potential Renewable Energy in GWh", label = scales::comma) + 
theme(legend.position = "right")

p3 <- plot_usmap(data = data, values ="reps_disease_death") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Respiratory Disease Deaths per 100,000", label = scales::comma)+
  theme(legend.position = "right")

p4 <- plot_usmap(data = data, values ="lung_cancer_per_100000") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Lung Cancer Diagnoses per 100,000", label = scales::comma)+
  theme(legend.position = "right")
data$lung_cancer_per_100000 <- as.integer(data$lung_cancer_per_100000)

p1
p2
p3
p4
```
```{r}
coal_data <- QBGlobalCoalTrackData
coal_data <- coal_data %>% rename(Subnational_Unit = `Subnational unit (province, state)`) %>% rename(Total_CO2 = 'Lifetime CO2') 

pop10 <- get_decennial(
  geography = "state",
  variables = "P001001") 
  pop10 <- pop10[-52,]

coal_data <- coal_data %>% select("Country", "Plant", "Subnational_Unit", "Total_CO2", "Status", "Accuracy") %>% filter(Country == "United States") %>% filter(Status == "operating" | Status == "retired")


coal_data_state <- coal_data %>% group_by(Subnational_Unit) %>% summarise(stateCO2 = sum(Total_CO2))
sum(coal_data$Total_CO2)

coal_data_state <- coal_data_state %>% rename(state = Subnational_Unit)
p5 <- plot_usmap(data = coal_data_state, values = "stateCO2") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Total CO2 emissions", label = scales::comma) + 
  theme(legend.position = "right")

p5
```
