---
title: "HealthCrosswalk"
author: "Quinn Bankson"
date: "2023-04-13"
output: html_document
---

```{r setup}
```


```{r libraries}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
library(stringr)
#install.packages("tidyr")
library(tidyr)
```

```{r read files}
crossw <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/countycrosswalk.csv")

aqi <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/annual_aqi_by_county_2014.csv")

outcomes <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Output/health_outcomes_2014.csv")
```

```{r correct names}
colnames(crossw)[1] <- "County"
colnames(crossw)[2] <- "State"
colnames(crossw)[3] <- "FIPS"

crossw <- crossw %>% select(County, State, FIPS)

crossw <- crossw %>%
  filter(County != "County Name")

```

```{r}

crossw <- crossw %>%
  mutate(County = str_to_title(tolower(County)))
```


```{r}
outcomes <- outcomes %>%
  separate(Location, into = c("County", "State"), sep = ", ", remove = FALSE)

outcomes <- outcomes %>%
  filter(!is.na(State))

```

```{r}
# join AQI and Outcomes, there will be all 3000+ Outcomes visible and only 1000ish AQI present

joined_dv_iv <- left_join(outcomes, aqi, by = c("County" = "County", "State" = "State"))
view(joined_dv_iv)
```

```{r}
# I intend to join the countycoords tibble which has county, state, 

```

