---
title: "DOrchid_analysis_1"
author: "Quinn Bankson"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}

```
```{r}
library(tidyverse)
library(ggplot2)
library(moderndive)
library(GGally)
library(janitor)
library(dplyr)
```

```{r}
coalplants <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/CoalPlants2.csv")
```

```{r}
colnames(coalplants)
coalplants <- clean_names(coalplants)
coalplants <- coalplants %>% filter(country == "United States")
coalplants <- coalplants %>% select(parent_id, unit, subnational_unit_province_state, plant, status, year, local_area_taluk_county, latitude, longitude )
coalplants <- rename(coalplants, county = local_area_taluk_county)
```
```{r}
counties <- read_csv(file = "/Users/mac/Documents/R Assignments PLCY 715/final-team-projects-darkorchid/DarkOrchid/Bankson/uscounties.csv")
head(counties)
colnames(counties)
county_center <- counties %>% select(county, state_name, lat, lng)

```
```{r}
joined_locs <- full_join(county_center, coalplants, by = "county")
joined_locs2 <-left_join(county_center, coalplants, by = "county")
```


```{r}
coalplants_op <- coalplants %>% filter(status == "operating")
coalplants_op <- distinct(coalplants_op, plant, .keep_all = TRUE)
```

```{r}
coal_plants <- coalplants_op %>% select("latitude", "longitude","subnational_unit_province_state", "plant")
coal_plants <- rename(coal_plants, long= longitude, lat = latitude)
coal_plants <- rename(coal_plants, state = subnational_unit_province_state, name = plant)
county_centroids <- county_center
county_centroids <- rename(county_centroids, long = lng)
#county_centroids <- filter(county_centroids, state_name == "Texas")
```

```{r}
#install.packages("geosphere")
library(geosphere)
library(dplyr)
library(naniar)

coal_plants <- coal_plants %>% 
  filter(!is.na(long))
coal_plants <- coal_plants %>% 
  filter(!is.na(lat))

county_centroids <- county_centroids %>% 
  filter(!is.na(long))
county_centroids <- county_centroids %>% 
  filter(!is.na(lat))

#dist_mat <- apply(county_centroids[, c("long", "lat")], 1,function(x) apply(coal_plants[, c("long", "lat")], 1, function(y) distm(x,y)))

#min_dist <- apply(dist_mat, 1, function(x) {
 # if (all(is.na(x))) NA
 # else x[which.min(x[!is.na(x)])]
#})
#county_centroids <- county_centroids[complete.cases(county_centroids), ]

```

```{r}
library(dplyr)
library(geosphere)

# filtering to be sure
coal_plants <- na.omit(coal_plants)

# calculaing distances with the matrix and geosphere package
distances <- geosphere::distm(county_centroids[, c("long", "lat")], coal_plants[, c("long", "lat")])

# minimum distance per county
min_distances <- apply(distances, 1, min)

# add the new column to the county_centroids dataframe using mutate
county_centroids <- county_centroids %>% 
  mutate(distance_to_nearest_plant = min_distances)

coords_distance <- county_centroids
```

```{r}
```

