---
title: "Darkorchid4_Merged_Data"
output: html_document
date: "2023-02-20"
---
```{r}
library(tidyverse)
library(tidycensus)
library(ggplot2) 
library(ggmap)
library(geosphere)
library(sp)
library(rgdal)
library(rgeos)
library(maps)
library(GADMTools)
library(maptools)
library(countrycode)
library(usmap)
library(ggpubr)
data("world.cities")
head(world.cities)

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)


Hathaway_data <- new_cleaned_data_excel_715 
Hathaway_data <- clean_names(Hathaway_data)
#reading in Paige's data and cleaning variable names

Leinweber_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Leinweber/usretechnicalpotential.csv") %>% clean_names()
#reading in Eric's data and cleaning variable names

Norwood_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHubRepository/final-team-projects-darkorchid/DarkOrchid/Norwood/usa_lung_cancer_by_state.csv") %>% clean_names()
Norwood_data <- Norwood_data[-c(52:92), ] %>% select(-c("x3", "x4", "x5", "x6", "x7"))
#reading in Betsy's data, cleaning variable names, and getting rid of NA columns/rows

Bankson_data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Bankson/QBCleanerData/grouped_data.csv") %>% clean_names()
#reading in Quinn's data and cleaning variable names

Merged_Darkorchid4_Data <- merge(Hathaway_data, Leinweber_data, by = "state")
Merged_Darkorchid4_Data <- merge(Merged_Darkorchid4_Data, Norwood_data, by="state")
Merged_Darkorchid4_Data <- merge(Merged_Darkorchid4_Data, Bankson_data, by = "state")
#merging all data frames by "state" variable

write_csv(Merged_Darkorchid4_Data, "/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Merged_DarkOrchid4_Dataset.csv")


```


```{r}

data <- read_csv("/Users/ericleinweber/Desktop/PLCY 715 GitHub Repository/final-team-projects-darkorchid/DarkOrchid/Merged_DarkOrchid4_Dataset.csv")

data <- data %>% rename(reps_disease_death = chronic_lower_respiratory_disease_deaths_per_100_000_people)


data %>% ggplot(aes(x = allpower_g_wh, y = reps_disease_death)) +
  geom_point()

usa <- sf::st_read(system.file("shape/nc.shp", package="sf"))

p1 <- plot_usmap(data = data, values ="stateco2") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Total CO2 emissions", label = scales::comma) + 
  theme(legend.position = "right")
p2 <- plot_usmap(data = data, values ="allpower_g_wh") + 
scale_fill_continuous(low = "white", high = "blue",name = "Potential Renewable Energy in GWh", label = scales::comma) + 
theme(legend.position = "right")

p3 <- plot_usmap(data = data, values ="reps_disease_death") + 
  scale_fill_continuous(low = "white", high = "blue",name = "Respiratory Disease Deaths per 100,000", label = scales::comma)+
  theme(legend.position = "right")
ggarrange(p1 + p2 + p3, 
          labels = c("A", "B", "C"))

```

